### ISSUE TITLE
Browser performance bad with lots of very small links

### ISSUE THREAD

**Issue by iimog** [AliTVTeam/AliTV-perl-interface#102]
If there are a lot of very small links the browser performance gets bad (loading times of up to a minute, or hanging). See #101 
Performance is drastically improved if this small links are filtered out - which is not difficult to do in perl.
There are two possible solutions here:
1. Add options to the yml for link filtering by length (and identity)
2. Automatically guess good cutoffs for link length (and identity)

**Comment by greatfireball** [comment]
This issue is addressed by the alitv-filter.pl script. It filters and removes filtered elements from a generated JSON file. The filter criteria are obtained from the JSON itself or via command line. The script is available since version 1.0.0 (9a2789d6ce18e47f7551cbddec6b7e9f1796ad42).
