### ISSUE TITLE
Unable to load alignment module

### ISSUE THREAD

**Issue by iimog** [AliTVTeam/AliTV-perl-interface#149]
From a user (via mail):

> i have installed all the dependency package for alitv as per the github
> instruction. i want to create image for custom genomes. i have made yml
> file as per the tutorials.
> 
> i am getting following error
> 
> FATAL - Unable to load alignment module 'AliTV::Alignment::lastz' at
> /data/ngs/programs/AliTV-perl-interface/bin/../lib/AliTV/Script.pm line 123.

**Comment by mictadlo** [comment]
me too:

```
perl -Ilib bin/alitv.pl ../../../alitv/*.fasta > BAFB.json
FATAL - Unable to load alignment module 'AliTV::Alignment::lastz' at bin/alitv.pl line 117.

Unable to load alignment module 'AliTV::Alignment::lastz' at bin/alitv.pl line 117.
```
Any updates?

**Comment by iimog** [comment]
Hi @mictadlo thanks for reporting, that you have this issue as well. The syntax of your command indicates that you are not using the latest version of `AliTV-perl-interface` (the `-Ilib` option is no longer required and the `.json` file will not be given on `STDOUT`). Could you please update `AliTV-perl-interface` and try again like this:

```
perl bin/alitv.pl --project BAFB ../../../alitv/*.fasta
```

My problem currently is that I can not replicate this error and therefore I can not effectively debug it.

**Comment by maedat** [comment]
I also got the same error. 

In my case, I had forgotten to do 

``
cpanm --installdeps .
``

on "/AliTV/AliTV-perl-interface" (lol). 

After that, my alitv.pl is working well.

**Comment by iimog** [comment]
Thanks @maedat for reporting. @mictadlo can you please try if this fixes it for you as well?

**Comment by von-elfen** [comment]
> I also got the same error.
> 
> In my case, I had forgotten to do
> 
> `cpanm --installdeps .`
> 
> on "/AliTV/AliTV-perl-interface" (lol).
> 
> After that, my alitv.pl is working well.

It work! Thank you!!
