### ISSUE TITLE
Different rounding of identity in links and filters

### ISSUE THREAD

**Issue by iimog** [AliTVTeam/AliTV-perl-interface#155]
This error is a little subtle and I stumbled across it by chance. When you run alitv.pl on the two sequences in [this gist](https://gist.github.com/iimog/5267a9046925a7e2834b96a2c61d8674) like this:
```
alitv.pl --project out seq0.fa seq1.fa
```
you end up with the json file also in the gist. When you visualize this file in the AliTV web interface you do not see any alignment despite the two sequences being almost identical.

Upon closer inspection I found the error: The `filters.links.maxLinkIdentity` is dynamically set to the link with highest identity found (with lots of precision), in this case: `99.8955395382848`.
However the identity for the link is rounded to one decimal position so is `99.9`.
As this is higher than the `maxLinkIdentity` the link is not shown. This is clearly a bug.

I can imagine multiple ways to address this issue:
1. do not set `maxLinkIdentity` dynamically, rather always set it to 100
2. round `maxLinkIdentity` and the separate links to the same number of decimal points

As a workaround if this case happens it helps to re-adjust the identity slider (set it a little lower, apply, set it to 100% and apply again). In this case with 99.89 it looks like it is fixed at 100 already...

**Comment by greatfireball** [comment]
100% agree, and the problem is the same or at least similar for `filters.links.minLinkIdentity`

My suggested solution would be:
1) trunc to percent for `filters.links.minLinkIdentity`
2) trunc to percent for `filters.links.maxLinkIdentity+1` or set it to 100

This would lead to integer values for both values which include the true values within their range.

Any comments @iimog

**Comment by iimog** [comment]
Sounds like a good and practical solution.

**Comment by greatfireball** [comment]
I will prepare a solution tonight.
