### ISSUE TITLE
reduce the number of alignment

### ISSUE THREAD

**Issue by 444thLiao** [AliTVTeam/AliTV-perl-interface#165]
If the tree file is provided, the pairwise alignment should be reductant?

I think reducing the number of alignment with given tree file is better.

**Comment by iimog** [comment]
Hi @444thLiao,

 thanks for reporting this issue. I'm not sure if I fully understand your question so here is a quick overview of how the tree file is handled in AliTV:
The tree when passed to `alitv.pl` is converted into a `json` structure suitable for visualization with the AliTV web interface. It is not used to filter or sort the genomes. When genomes are not ordered concordant with the tree it is hidden (and a message is displayed instead).

Some questions:
 - Is your suggestion for the perl stage (at the point where alignments are calculated) or at the javascript stage (at the point where alignments are visualized)?
 - do you suggest to remove/hide genomes not present in the tree?
 - do you suggest automatically ordering genomes in a way concordant with the tree?

Best,
Markus

**Comment by 444thLiao** [comment]
Thank you for your quick reply @iimog ,

Here are my understanding and supplemental suggestions.
For my point of view, the tree provided is majorly used to **sort** these genomes with user-defined distance or phylogenetic relationship. So for the first question, I think it would be nice to do the modification under perl stage. 

There are several reasons:
for me, I have 140+ genomes need to do the alignment and visualization. Of course, I preferred linear layout instead of circular layout. Now, pairwise alignment is time wasted for me.
And reducing the data within `link` under the json also speed up the processing time for `html`

For the remained questions, I suggest hiding instead of removing. I think ordering genomes which are consistent with the tree should be more favourable for me.

Best regards,
tianhua

**Comment by iimog** [comment]
Thanks for the clarification. I think what you are suggesting are very valuable features. Especially for a case like yours with such a large amount of genomes. @greatfireball do you think you could easily implement this in the perl part?
One complication is that the tree does not yield a unique order of genomes. One practical solution for that problem could be to use rooted trees, bring them in ladderized format and use the resulting order of genomes. So I think it is not trivial but a quick practical solution could be possible.
