### ISSUE TITLE
Unable to find lastz

### ISSUE THREAD

**Issue by tlkane** [AliTVTeam/AliTV-perl-interface#170]
I'm trying to use AliTV for the first time and I keep getting the same error: 

FATAL - Unable to find lastz at /Users/taylorkane/Desktop/newfile.nosync/AliTV-perl-interface/bin/../lib/AliTV.pm line 99.

lastz is in the same directory as alitv.pl, and I tried un- and reinstalling it, but I still getting the same issue. Any help is appreciated!

**Comment by iimog** [comment]
AliTV tries to find `lastz` in your `PATH`. So if you can call `lastz` directly on the command line, it should be found by AliTV, as well. You can add the folder containing `lastz` to the `PATH` temporarily, like this:

```bash
export PATH=$PATH:/Users/taylorkane/Desktop/newfile.nosync/AliTV-perl-interface/bin/
```

Then run `alitv.pl` in the same terminal window. This change of `PATH` is only valid for the terminal you run it in and will be lost when you close and open it again.

**Comment by iimog** [comment]
I assume, that solved your issue. Feel free to re-open, if it didn't.
