### ISSUE TITLE
Genome order according to the given tree

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV-perl-interface#38]
Currently my brain is blocked... How to obtain the best genome order for a given tree?

Any ideas?

**Comment by iimog** [comment]
For rooted trees it might be a good idea to ladderize it.
From http://treegraph.bioinfweb.info/Help/wiki/Ladderizing

> To ladderize a tree means sorting the nodes on one level by the count of their subnodes (on all levels under the node). It usually makes understanding the tree easier. 
> For unrooted trees a (random?) root has to be chosen.
