### ISSUE TITLE
Move repo to AliTVTeam organization

### ISSUE THREAD

**Issue by iimog** [AliTVTeam/AliTV-perl-interface#43]
Name can be AliTV-perl or AliTV-script or AliTV-generate or AliTV-prepare.

**Comment by greatfireball** [comment]
Ups... Sry... I kept `AliTV-perl-interface`... Hope that is okay.. Otherwise I will change the name.

**Comment by iimog** [comment]
It's alright now its AliTV-perl-interface. Let's stick with that.
