### ISSUE TITLE
Error with huge sequence sets

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV-perl-interface#50]
```
Error in tempfile() using template tempXXXXX.maf: Could not create temp file temp50E5h.maf: Too many open files at [...]/AliTV-perl-interface/lib/AliTV/Alignment/lastz.pm line 70.
```

```

**Comment by greatfireball** [comment]
I have written a small simulation script to simulate a sequence set (please see the attached file).

It generates a set of 100 sequences named seq1 to seq100 each with length of 500 nucleotides.

[generate_100_random_sequences.pl.txt](https://github.com/AliTVTeam/AliTV-perl-interface/files/399258/generate_100_random_sequences.pl.txt)

**Comment by greatfireball** [comment]
Generation of to example files using the following code:
`for i in 17871 21764; do perl ./generate_100_random_sequences.pl.txt "$i" >"$i".fa`

An running the set with `alitv.pl` produced no error after more then 1/3 of the alignments
`INFO - Finished 7596. alignment (12504 to go; 37.79 % done)`

**Comment by greatfireball** [comment]
Okay... Ran without errors and produced a `JSON` file. Nevertheless, it is incredibly slow!!!

[output.json.txt](https://github.com/AliTVTeam/AliTV-perl-interface/files/399418/output.json.txt)

**Comment by greatfireball** [comment]
Need to be checked by @iimog and Sonja

**Comment by greatfireball** [comment]
Please recheck @iimog

**Comment by iimog** [comment]
Fixed
