### ISSUE TITLE
Import of existing alignments

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV-perl-interface#51]
Precomputed alignments need to be importable.

**Comment by iimog** [comment]
Support of MAF files is very important as indicated by user requests.

**Comment by mjfi2sb3** [comment]
Yes, I look forward to receiving this update! Keep up the good work

**Comment by greatfireball** [comment]
Finally the feature was implemented and tested... Hope it is not to late @mjfi2sb3 It is avaiable since version 1.0.0 (9a2789d6ce18e47f7551cbddec6b7e9f1796ad42)
