### ISSUE TITLE
yml as input plus project name

### ISSUE THREAD

**Issue by greatfireball** [AliTVTeam/AliTV-perl-interface#90]
Does not seem to work...

```
perl -I lib bin/alitv.pl data/chloroset/input.yml

***********************************************************************
*                                                                     *
*  AliTV perl interface                                               *
*                                                                     *
***********************************************************************

You are using version v0.1.12.
INFO - Created temporary folder at '/tmp/_Q2WDyftc2'
INFO - Starting alignment generation... (36 alignments required)
[...]

```

`json/log/map` files have the name `autogen_XXXXX.*`

But if proving a project name I am receiving a warning message:

```
perl -I lib bin/alitv.pl --project new_run data/chloroset/input.yml
YML file specified, therefore the project name was overwritten by 'input'!

***********************************************************************
*                                                                     *
*  AliTV perl interface                                               *
*                                                                     *
***********************************************************************

You are using version v0.1.12.
INFO - Created temporary folder at '/tmp/wDTDHkuKA3'
INFO - Starting alignment generation... (36 alignments required)
```

But `json/log/map` are now named as expected `input.*`

**Comment by iimog** [comment]
In `alitv.pl` lines 49ff there is:
```perl
if ($project)
{
	$project = fileparse($yml, qr/\Q.yml\E/i);
	warn "YML file specified, therefore the project name was overwritten by '$project'!\n";
}
```
So project is only overwritten with the basename of the `.yml` file if it has been explicitly set. This leads to the strange behaviour that if `--project` is not used together with a `.yml` file the output is named `autogen...` but if you set a project name it is ignored and the name of the `.yml` file is used.

In my opinion the desired behaviour is to always use the project name if it has been explicitly set using `--project` and use the basename of the `.yml` file only if none is provided. The `autogen` names would then only be necessary for usage with `.fasta` files and no `--project`

**Comment by greatfireball** [comment]
Okay, so we have the following scenarios:

1. Project set via `--project` option, no influence by YAML or sequence files
2. No project set, but YAML file as single parameter
3. No Project set, no YAML file provided  and therefore assuming that the user provided a set of sequence files

Output for different scenarios:
1. We are using the provided project name
2. The basename of the YAML file is used as project name
3. The project name will be autogenerated and the YAML file is based on that autogenerated project name

Would that match your expectations @iimog ?

**Comment by iimog** [comment]
Perfect summary of my expectations :smiley:
